checks:
    php:
        code_rating: true
        duplication: true
tools:
    php_sim: true
    php_code_sniffer:
        config:
            standard: "PSR2"
    php_changetracking: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    external_code_coverage:
        runs: 5

filter:
    excluded_paths:
        - src/Zie/DeviceDetector/Tests/*