language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer install --prefer-source

script:
  - cp phpunit.xml.dist phpunit.xml
  - phpunit -c phpunit.xml

notifications:
  email:
    - damian.zientalak@gmail.com