language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then rm phpspec.yml.dist; fi
  - if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then cp phpspec-hhvm.yml.dist phpspec.yml.dist; fi

after_script:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi

script:
  - mkdir -p build/logs
  - php bin/rule_fastener
  - cp phpspec.yml.dist phpspec.yml
  - cp phpunit.xml.dist phpunit.xml
  - bin/phpspec run -c phpspec.yml
  - bin/phpunit -c phpunit.xml

notifications:
  email:
    - damian.zientalak@gmail.com