language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

services:
    - memcached
    - redis-server

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then pecl install riak-beta; fi"
  - sh -c "if [[ $TRAVIS_PHP_VERSION != 'hhvm' && `php-config --vernum` -ge 50500 ]] ; then pecl config-set preferred_state beta; printf "yes\n" | pecl install apcu ; else echo 'extension="apc.so"' >> ./tests/travis/php.ini ;fi"
  - composer install --prefer-source --dev --no-interaction
  - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then phpenv config-add ./tests/travis/php.ini; fi"

after_script:
  - php vendor/bin/coveralls -v

script:
  - mkdir -p build/logs
  - cp phpunit.xml.dist phpunit.xml
  - phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml

notifications:
  email:
    - damian.zientalak@gmail.com