language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

services:
    - memcached
    - redis-server

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - phpenv config-add travis/php.ini
  - composer --self-update
  - composer install --prefer-source --dev --no-interaction

after_script:
  - php vendor/bin/coveralls -v

script:
  - mkdir -p build/logs
  - cp phpunit.xml.dist phpunit.xml
  - phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml

notifications:
  email:
    - damian.zientalak@gmail.com