-
    patterns:
        -
            strategy: string
            value: Lutea
    capabilities:
        is_mobile: true
        display_width: 800
        display_height: 480
        brand_vendor: Base
        brand_model: Lutea
        design_weight: 130
        display_size: '3.5'
        display_type: TFT
-
    patterns:
        -
            strategy: string
            value: 'Lutea 2'
    capabilities:
        is_mobile: true
        display_width: 800
        display_height: 480
        brand_vendor: Base
        brand_model: 'Lutea 2'
        design_weight: 135
        display_size: '4.3'
        display_type: TFT
-
    patterns:
        -
            strategy: string
            value: 'Lutea 3'
    capabilities:
        is_mobile: true
        is_tablet: true
        display_width: 480
        display_height: 800
        brand_vendor: Base
        brand_model: 'Lutea 3'
        design_weight: 130
        display_size: '4'
        display_type: TFT
